server: 
  port: 8085

mybatis:
  mapper-locations:
  - mapper/**/*.xml
  
spring: 
  application: 
    name: merchant-eureka
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包      
    url: "jdbc:mysql://localhost:3306/workmerchant?characterEncoding=utf8&allowMultiQueries=true&useSSL=false"                    # 数据库名称
    username: root
    password: 123456
    dbcp2: 
      initial-size: 5                                         # 初始化连接数
      max-total: 5                                            # 最大连接数
      max-wait-millis: 200                                    # 等待连接获取的最大超时时间
      min-idle: 5                                             # 数据库连接池的最小维持连接数

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka